#
# This Makefile was generated by Code::Blocks IDE.
#

SRCS_f90d1 = \
NetcdfUtils_mod.f90 \
FieldWPS_mod.f90 \
merra2wrf.f90 \
MerraData_mod.f90 \
FieldWPSList_mod.f90 \
FileWPS_mod.f90 \
FileUnit_mod.f90 \
WrfRH_mod.f90 \
NamelistMerra_mod.f90 \
CheckSubsetBounds_mod.f90 \
FileUtils_mod.f90 

SRCS_d1 = \
.project 

SRCS_cbpd1 = \
merra2wrf.cbp 

OBJS_f90d1 = \
NetcdfUtils_mod.o \
FieldWPS_mod.o \
merra2wrf.o \
MerraData_mod.o \
FieldWPSList_mod.o \
FileWPS_mod.o \
FileUnit_mod.o \
WrfRH_mod.o \
NamelistMerra_mod.o \
CheckSubsetBounds_mod.o \
FileUtils_mod.o 

OBJS_d1 = \


OBJS_cbpd1 = \


SRC_DIR_f90d1 = 

SRC_DIR_d1 = 

SRC_DIR_cbpd1 = 
OBJS_DIR = obj/Debug/
EXE_DIR = bin/Debug/

EXE = merra2wrf
FC = gfortran
LD = gfortran
IDIR = -I/home/suleiman/local/include 
CFLAGS = -Wall -g  -J$(OBJS_DIR) $(IDIR)
LFLAGS = 
LIBS = -L/home/suleiman/local/lib -lnetcdff -lnetcdf 

VPATH = $(SRC_DIR_f90d1):$(OBJS_DIR):$(SRC_DIR_d1):$(OBJS_DIR):$(SRC_DIR_cbpd1):$(OBJS_DIR)
OBJS = $(addprefix $(OBJS_DIR), $(OBJS_f90d1) $(OBJS_d1) $(OBJS_cbpd1))

all : $(EXE)

$(EXE) : $(OBJS_f90d1) $(OBJS_d1) $(OBJS_cbpd1)
	@mkdir -p $(EXE_DIR)
	$(LD) -o $(EXE_DIR)$(EXE) $(OBJS) $(LFLAGS) $(LIBS)

$(OBJS_f90d1):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_f90d1)$(@:.o=.f90) -o $(OBJS_DIR)$@

$(OBJS_d1):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_d1)$(@:.o=.) -o $(OBJS_DIR)$@

$(OBJS_cbpd1):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_cbpd1)$(@:.o=.cbp) -o $(OBJS_DIR)$@

clean :
	rm -f $(OBJS_DIR)*.*
	rm -f $(EXE_DIR)$(EXE)

# Dependencies of files
NetcdfUtils_mod.o: \
    NetcdfUtils_mod.f90 \
    CheckSubsetBounds_mod.o
FieldWPS_mod.o: \
    FieldWPS_mod.f90
merra2wrf.o: \
    merra2wrf.f90 \
    FileUtils_mod.o \
    MerraData_mod.o \
    NamelistMerra_mod.o
MerraData_mod.o: \
    MerraData_mod.f90 \
    FieldWPS_mod.o \
    FileUnit_mod.o \
    FileUtils_mod.o \
    FileWPS_mod.o \
    WrfRH_mod.o
FieldWPSList_mod.o: \
    FieldWPSList_mod.f90 \
    FieldWPS_mod.o
FileWPS_mod.o: \
    FileWPS_mod.f90 \
    FieldWPS_mod.o
FileUnit_mod.o: \
    FileUnit_mod.f90
WrfRH_mod.o: \
    WrfRH_mod.f90
NamelistMerra_mod.o: \
    NamelistMerra_mod.f90 \
    FileUnit_mod.o \
    FileUtils_mod.o
CheckSubsetBounds_mod.o: \
    CheckSubsetBounds_mod.f90
FileUtils_mod.o: \
    FileUtils_mod.f90 \
    NetcdfUtils_mod.o

